### PR TITLE
Closes #111: Revisit LCP/ATF disabled templates

### LINKED ISSUE #111: Revisit disabled LCP/ATF tests to fix them and re-enable them
**Context**
We recently disabled many LCP/ATF tests (see the `enabled` values in `src/support/results/expectedResults` files); this allowed to clean Rocket-E2E results but it is not viable in the mid/long run. Those tests must either be re-enabled once fixed, or deleted if irrelevant.
A first investigation quickly started [here](https://wp-media.slack.com/archives/CUT7FLHF1/p1717758691667969)

**Expected behavior**
For each of the disabled templates, on mobile and/or desktop:
- Confirm manually with QA that, with wp-rocket develop branch, the LCP/ATF optimization is correctly applied (expected HTML modifications) on the template.
- If not, then log a GH issue and reference the template in it.
- Else, go to the wp-rocket DB and extract the LCP and viewport values for this tempalte in the mobile and/or desktop. Modify the expected results of the Rocket-E2E JSON file to match what you extracted in the DB. Then, re-run Rocket-E2E for this template and confirm it is now passing.

Additional note: We suspect some tests are failing because the template uses external images (from another host) that can sometimes be slower than the beacon execution. Several possibilities to discuss:
- Use the new filter to make the beacon execution later than normal, to avoid those cases.
- Move the images to the E2E website to avoid network issues
- Replace those templates with equivalents with images hosted on the E2E website.

**Acceptance Criteria**
- There are no disabled tests in LCP/ATF templates of Rocket-E2E. If there are some, they are associated to a GH issue on wp-rocket.
- Rocket-E2E is passing without errors for LCP/ATF tests.

### PR DESCRIPTION
**Pull request by Miraeld**
# Description

Fixes #111 

### Technical documentation

This PR contains fixes for the LCP tests we knew were failing and now are working properly after being fixed.
Most of the time, it was due to the fact images were on external domain which means they were loaded after the script run. Which means most of template changes are happening in [rocket-test-data](https://github.com/wp-media/rocket-test-data)

Before testing, please make sure you have the latest update of [rocket-test-data](https://github.com/wp-media/rocket-test-data). 

## Type of change
- [x] Bug fix (non-breaking change which fixes an issue).

# Checklists

## Feature validation

- [x] I validated all the Acceptance Criteria. If possible, provide sreenshots or videos.
- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.
- [x] I implemented built-in tests to cover the new/changed code.

## Documentation

- [x] I prepared the user documentation for the feature/enhancement and shared it in the PR or the GitHub issue.
- [x] The user documentation covers new/changed entry points (endpoints, WP hooks, configuration files, ...).
- [x] I prepared the technical documentation if needed, and shared it in the PR or the GitHub issue.

### CODE REVIEW

**Review by jeawhanlee — COMMENTED** [review]
### We still have this template: `lcp_rsponsive_imagegrid` failing for desktop

`Expected LCP for desktop - /wp-content/rocket-test-data/images/lcp/underwater.jpg for http://mike.e2e.rocketlabsqa.ovh/lcp_rsponsive_imagegrid is not present in actual - {"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/wedding.jpg"}`


`Expected Viewport for desktop - /wp-content/rocket-test-data/images/lcp/wedding.jpg for http://mike.e2e.rocketlabsqa.ovh/lcp_rsponsive_imagegrid is not present in actual - [{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testavif.avif"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/rocks.jpg"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testPng.png"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/mist.jpg"}]`

`Expected Viewport for desktop - /wp-content/rocket-test-data/images/file_example_JPG_100kB.jpg for http://mike.e2e.rocketlabsqa.ovh/lcp_rsponsive_imagegrid is not present in actual - [{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testavif.avif"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/rocks.jpg"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testPng.png"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/mist.jpg"}]`

`Expected Viewport for desktop - /wp-content/rocket-test-data/images/maxime-lebrun-6g3Akg708E0-unsplash.jpg for http://mike.e2e.rocketlabsqa.ovh/lcp_rsponsive_imagegrid is not present in actual - [{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testavif.avif"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/rocks.jpg"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testPng.png"},{"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/mist.jpg"}]`



### And for mobile, we have this:

`Expected LCP for mobile - https://discuss-assets.s3.amazonaws.com/original/3X/1/9/19823cc1f1f887d70755e0b500dd8ce2c51ba7f9.svg for http://mike.e2e.rocketlabsqa.ovh/lcp_no_dimension_svg is not present in actual - {"type":"img","src":"http://mike.e2e.rocketlabsqa.ovh/wp-content/rocket-test-data/images/lcp/testsvg.svg"}`

**Comment by Miraeld** [comment]
Everything is passing for me on my e2e env, + local tests as well. 

Are you sure all images get loaded when the script run on the template you mentioned @jeawhanlee ?

**Review by MathieuLamiot — APPROVED** [review]

**Comment by MathieuLamiot** [comment]
Pending QA feedback from @jeawhanlee about the flackiness (see [here](https://github.com/orgs/wp-media/projects/109/views/1?pane=issue&itemId=67649615))

**Comment by jeawhanlee** [comment]
I can confirm tests passing in the updated expectations for the templates when I set the filter `rocket_lcp_delay` to a higher value in my case (`5000`).

**Comment by jeawhanlee** [comment]
@MathieuLamiot This is ok to merge?

**Comment by MathieuLamiot** [comment]
With your confirmation for the E2E results, yes!

**Pull request merged**
