### PR TITLE
Enhancement/refactor smoke test

### LINKED ISSUE #133: Rework code using waitForLoadState('load'
**Context**
https://github.com/wp-media/wp-rocket-e2e/issues/54#issuecomment-2284827569

**Expected behavior**

Review usage of waitForLoadState('load', throughout the tool. For each occurrence:
- Consider using another waitFor function instead, for instance: waitForSelector. This allows us to only wait for a specific element (for example the Settings Saved banner after saving changes) which will be less flaky.

- If the load event is necessary, introduce a retry mechanism so that we retry the last action if the timeout is reached.

**Acceptance Criteria**
waitForLoadState('load' must not be used in the codebase without a retry strategy around it.

### PR DESCRIPTION
**Pull request by Mai-Saad**
# Description
This PR attempts to solve smoke test errors related to `this.page.waitForLoadState('load', { timeout: 30000 });` and refactor where needed for logic

Note: still some tests are failing so it's WIP

Fixes #133 partially

## Type of change

- [ ] New feature (non-breaking change which adds functionality).
- [ ] Bug fix (non-breaking change which fixes an issue).
- [x] Enhancement (non-breaking change which improves an existing functionality).
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as before).
- [ ] Sub-task of #(issue number)
- [ ] Release

## Detailed scenario

Sometimes tests are failing as `this.page.waitForLoadState('load', { timeout: 30000 });` timeout so here we replaced some of waitforload with assertion + some logic refactor

### Documentation

- It replaces `timeout:30000` in some places with an assertion and decreases wait time in other parts 
- It refactors logic in some parts to remove unneeded steps

### New dependencies

No

### Risks

No

# Mandatory Checklist

## Code validation

- [x] I triggered all changed lines of code at least once without new errors/warnings/notices.

## Code style
- [x] I wrote a self-explanatory code about what it does.
- [x] I did not introduce unnecessary complexity.

# Additional Checks
- [x] In the case of complex code, I wrote comments to explain it.

### CODE REVIEW

**Comment by Mai-Saad** [comment]
3.17 Results on PR now https://filetransfer.io/data-package/tncWYOQg#link failed test is due to DB error (which shall be ignored) .. @wp-media/engineering-plugin-team can anyone please pull the branch and `npm run test:smoke` there to confirm results.
Screenshot from 2024-09-18 11-58-35

Note: sometimes and probably with low internet connection, tests may fail and timeout

**Comment by hanna-meda** [comment]
@Mai-Saad, same results as with you on my end, 7 passed 1 failed, but a different one. Test results below:
[hannameda-wp-rocket-e2e-test-results-cucumber-report-html-2024-09-18-18_00_21.pdf](https://github.com/user-attachments/files/17046038/hannameda-wp-rocket-e2e-test-results-cucumber-report-html-2024-09-18-18_00_21.pdf)

Screenshot 2024-09-18 at 18 04 22

**Comment by MathieuLamiot** [comment]
A couple of failing tests because of the already existing table errors. So I'd say good on my side.
[debug-roll-back-from-the-tools-tab.log](https://github.com/user-attachments/files/17048260/debug-roll-back-from-the-tools-tab.log)
[debug-enable-all-features.log](https://github.com/user-attachments/files/17048259/debug-enable-all-features.log)


A few notes:
- This must be prioritized: https://github.com/wp-media/wp-rocket-e2e/issues/67 ; it is the main cause of failing smoke tests currently it seems. Added the label and will prioritize
- previous_stable must be 3.16 or above, otherwise import/export tests will fail because of the old UI of enabling/disabling separate cache.
- If using up-to-date dependencies (with npm update), then the backstop reference creation fails. we will need a dedicated GH issue to follow-up on dependency updates, but this is not for now.

**Comment by Miraeld** [comment]
It works on my side, with errors mentioned before by @MathieuLamiot .
Good on my side too.

**Review by Miraeld — APPROVED** [review]

**Pull request merged**
